### ISSUE TITLE
V2.4 Introduced Failure

### ISSUE THREAD

**Issue by Rebel154** [linusg/rpi-backlight#36]
I updated from V2.2 to V2.4 on my two Raspberry Pi's  (a 3A+ and a 3B+, both running Python 3.7.3) yesterday, and now I get an error message when running

`rpi-backlight -b 100`

The error message is as follows:

`Traceback (most recent call last):
  File "/home/pi/.local/bin/rpi-backlight", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/rpi_backlight/cli.py", line 104, in main
    backlight.brightness = args.set_brightness
  File "/home/pi/.local/lib/python3.7/site-packages/rpi_backlight/__init__.py", line 212, in brightness
    self._set_value("tinker_mcu_bl", self._denormalize_brightness(value))
  File "/home/pi/.local/lib/python3.7/site-packages/rpi_backlight/__init__.py", line 100, in _set_value
    raise e
  File "/home/pi/.local/lib/python3.7/site-packages/rpi_backlight/__init__.py", line 96, in _set_value
    (self._backlight_sysfs_path / name).write_text(str(value))
  File "/usr/lib/python3.7/pathlib.py", line 1218, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/platform/ff3e0000.i2c/i2c-8/8-0045/tinker_mcu_bl'
`

I have uninstalled rpi-backlight, rebooted, reinstalled v2.4, rebooted again and the error still pops up when running the above command. It appears as though it's looking for a Tinker board directory when one doesn't exist.

Thank you.

**Comment by linusg** [comment]
Thank you for reporting this issue, I'm able to reproduce it. Working on a fix now.

**Comment by linusg** [comment]
Fix released in v2.4.1, thanks again!
