### ISSUE TITLE
rpi-backlight off

### ISSUE THREAD

**Issue by p1r473** [linusg/rpi-backlight#39]
What is the expected outcome of `rpi-backlight off` and `rpi-backlight on`?
I understand I am supposed to be using `-p off` and `-p on`

However I mistakenly tried just `off` and `on` and found it crashes.
On a Raspberry Pi 4B

rpi-backlight on
```
Traceback (most recent call last):
  File "/usr/local/bin/rpi-backlight", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/cli.py", line 80, in main
    backlight_sysfs_path=args.sysfs_path,
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/__init__.py", line 75, in __init__
    self._max_brightness = self._get_value("max_brightness")  # 255
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/__init__.py", line 92, in _get_value
    raise e
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/__init__.py", line 84, in _get_value
    return int((self._backlight_sysfs_path / name).read_text())
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'on/max_brightness'
```
rpi-backlight off
```
Traceback (most recent call last):
  File "/usr/local/bin/rpi-backlight", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/cli.py", line 80, in main
    backlight_sysfs_path=args.sysfs_path,
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/__init__.py", line 75, in __init__
    self._max_brightness = self._get_value("max_brightness")  # 255
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/__init__.py", line 92, in _get_value
    raise e
  File "/usr/local/lib/python3.7/dist-packages/rpi_backlight/__init__.py", line 84, in _get_value
    return int((self._backlight_sysfs_path / name).read_text())
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'off/max_brightness'
```

**Comment by linusg** [comment]
The positional CLI argument is the sysfs base directory, which can be used with a fake sysfs for testing or the special `:emulator:` value. See https://rpi-backlight.readthedocs.io/en/latest/usage.html#command-line-interface.
