### ISSUE TITLE
Fails on bookworm 

### ISSUE THREAD

**Issue by delovelady** [linusg/rpi-backlight#63]
> cat /etc/os-release
    PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
    NAME="Debian GNU/Linux"
    VERSION_ID="12"
    VERSION="12 (bookworm)"
    VERSION_CODENAME=bookworm
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
    dennis@dtclock:/home/dennis   08/16 05:48:27

> .local/bin/rpi-backlight --get-brightness
Traceback (most recent call last):
  File "/home/dennis/.local/bin/rpi-backlight", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dennis/.local/lib/python3.11/site-packages/rpi_backlight/cli.py", line 80, in main
    backlight = Backlight(
                ^^^^^^^^^^
  File "/home/dennis/.local/lib/python3.11/site-packages/rpi_backlight/__init__.py", line 82, in __init__
    self._max_brightness = self._get_value("max_brightness")  # 255
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

~                                                         
  File "/home/dennis/.local/lib/python3.11/site-packages/rpi_backlight/__init__.py", line 99, in _get_value

~                                                         
    raise e
  File "/home/dennis/.local/lib/python3.11/site-packages/rpi_backlight/__init__.py", line 91, in _get_value
    return int((self._backlight_sysfs_path / name).read_text())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1045, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/backlight/rpi_backlight/max_brightness'

**Comment by linusg** [comment]
Duplicate of #60.
